### ISSUE TITLE
Two different archives for the same version

### ISSUE THREAD

**Issue by mboisson** [QEF/q-e#5]
Why are
https://github.com/QEF/q-e/releases/download/qe-6.3/qe-6.3.tar.gz
and 
https://github.com/QEF/q-e/archive/qe-6.3.tar.gz

two different archives, with two different directory structure and a few different files ?

This causes confusion and break build scripts for one of the two versions.

**Comment by pietrodelugas** [comment]
the  //archive/qe-6.3.tar.gz is the archive generated automatically by GitHub whenever you create a  tag, it is an exact picture of the source tree at the moment of the tag creation. 

The  one under releases/download is the package tarball as it has been  chosen to distribute it.
 Both tarballs are perfectly OK,  there is no substantial difference between the two,  just as you noticed a different name of the top directory  and few different files.  The code is the same, so you can download indifferently either one or the other. 
I downloaded and compiled the two archives; the build scripts work perfectly  in both cases as it has to be because   the configure script detects by itself the name of the topdir.  

We will take care of using a different name for the uploaded package next time, renaming it this time may   cause more confusion though.

**Comment by mboisson** [comment]
The build scripts *from* the archive might work correctly, but packagers for HPC centers typically wrap installers around with other software, such as EasyBuild, Spack, or other scripts to create RPMs. Many of those verify checksums (which are different for both archives), and rely on specific names/directory structure. When these change, one has to modify the wrapper accordingly. If there are two different archives for a single version, it then creates ambiguity as to which version the script wrapper was written for.

**Comment by pietrodelugas** [comment]
As I wrote before this time we can't do anything anymore.  Next time we will take care to chose a different name for the *distribution* package.  
For automated installation with scripts maybe it is better to rely only on locations  which obey to  a fixed pattern like those of the  archives created automatically by github which depend only on the repository name and the release tag.
